import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.text.NumberFormat;
import java.util.Locale;

public class HistorialDeuda extends java.awt.Frame {
    
    private int rutDeudor;
    private String nombreDeudor;
    private java.awt.Frame ventanaPadre;
    
    private String usuario;
    private boolean permisos;
    
    private int filaSeleccionada = -1;
    private int idBoletaSeleccionada = -1;
    
    Connection conex=null;
    Statement stm=null; 
    
   
    private DefaultTableModel modeloHistorial;
    private DefaultTableModel modeloDetalle;

    /**
     * Creates new form HistorialDeuda
     */
    public HistorialDeuda(int rutDeudor, String nombreDeudor, java.awt.Frame ventanaPadre) {
        this(rutDeudor, nombreDeudor, ventanaPadre, "usuario_desconocido", true);
    }    
    
  
    public HistorialDeuda(int rutDeudor, String nombreDeudor, java.awt.Frame ventanaPadre , String usuario , boolean permisos) {
        this.rutDeudor = rutDeudor;
        this.nombreDeudor = nombreDeudor;
        this.ventanaPadre = ventanaPadre;
        this.usuario = usuario;
        this.permisos = permisos;
        conectar();
        initComponents();
        configurarTablas();
        cargarDatosCliente();
        cargarHistorialDeudas();
        agregarListeners();
        configurarSegunPermisos();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblRut = new javax.swing.JLabel();
        lblRutExample = new javax.swing.JLabel();
        lblDeudaTotal = new javax.swing.JLabel();
        lblPrecioExample = new javax.swing.JLabel();
        lblHistorial = new javax.swing.JLabel();
        panelHistorial = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();
        panelDetalle = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        lblProductosBoleta = new javax.swing.JLabel();
        btnVerProductos = new javax.swing.JButton();
        btnPagarDeuda = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Historial de Deudas -");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("NombreCiente");

        lblRut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRut.setForeground(new java.awt.Color(102, 102, 102));
        lblRut.setText("RUT: ");

        lblRutExample.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRutExample.setForeground(new java.awt.Color(102, 102, 102));
        lblRutExample.setText("RutCliente");

        lblDeudaTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDeudaTotal.setText("Deuda Total Pendiente: ");

        lblPrecioExample.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrecioExample.setForeground(new java.awt.Color(255, 0, 51));
        lblPrecioExample.setText("$2000 ejemplo");

        lblHistorial.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHistorial.setText("Historial de Transacciones");

        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        panelHistorial.setViewportView(tablaHistorial);

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        panelDetalle.setViewportView(tablaDetalle);

        lblProductosBoleta.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblProductosBoleta.setText("Productos de la boleta seleccionada: ");

        btnVerProductos.setText("Ver Productos");
        btnVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerProductosActionPerformed(evt);
            }
        });

        btnPagarDeuda.setText("Pagar Deuda");

        btnCerrar.setBackground(new java.awt.Color(51, 153, 255));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Volver");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHistorial)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblRut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRutExample)
                                .addGap(54, 54, 54)
                                .addComponent(lblDeudaTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPrecioExample, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                            .addComponent(panelDetalle)
                            .addComponent(lblProductosBoleta)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVerProductos)
                                .addGap(23, 23, 23)
                                .addComponent(btnPagarDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRut)
                    .addComponent(lblRutExample)
                    .addComponent(lblDeudaTotal)
                    .addComponent(lblPrecioExample))
                .addGap(29, 29, 29)
                .addComponent(lblHistorial)
                .addGap(18, 18, 18)
                .addComponent(panelHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblProductosBoleta)
                .addGap(4, 4, 4)
                .addComponent(panelDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagarDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    
    private void configurarSegunPermisos() {
        setTitle("Historial de Deudas - Usuario: " + usuario);
    }
    
    public void conectar(){
        String url="jdbc:mysql://localhost:3306/vistaalmar";
        String user="root";
        String pass="";
        try{
            conex=DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"error en conexion "+ex,"error",1);
        }       
    }
    
    private void configurarTablas() {
        String[] columnasHistorial = {"ID Boleta", "Fecha", "Monto Total", "Pagado", "Saldo", "Estado"};
        modeloHistorial = new DefaultTableModel(columnasHistorial, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaHistorial.setModel(modeloHistorial);
        
        tablaHistorial.getColumnModel().getColumn(0).setPreferredWidth(80);
        tablaHistorial.getColumnModel().getColumn(1).setPreferredWidth(100);
        tablaHistorial.getColumnModel().getColumn(2).setPreferredWidth(100);
        tablaHistorial.getColumnModel().getColumn(3).setPreferredWidth(80);
        tablaHistorial.getColumnModel().getColumn(4).setPreferredWidth(100);
        tablaHistorial.getColumnModel().getColumn(5).setPreferredWidth(80);
        
        String[] columnasDetalle = {"Producto", "Cantidad", "Precio Unitario", "Subtotal"};
        modeloDetalle = new DefaultTableModel(columnasDetalle, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaDetalle.setModel(modeloDetalle);
    }    
    
    private void cargarDatosCliente() {
        jLabel2.setText(nombreDeudor);
        lblRutExample.setText(String.valueOf(rutDeudor));
    }



    private void cargarHistorialDeudas() {
        try {
            modeloHistorial.setRowCount(0);
            int deudaTotal = 0;


            String sql = "SELECT d.deudaId, d.idBoleta, d.fechaDeuda, d.estaPagado, d.montoPagado, " +
                         "b.totalFiado " +
                         "FROM deudas d " +
                         "INNER JOIN boletas b ON d.idBoleta = b.idBoleta " +
                         "WHERE d.rutDeudor = ? " +
                         "ORDER BY d.fechaDeuda DESC";  

            PreparedStatement pstmt = conex.prepareStatement(sql);
            pstmt.setInt(1, rutDeudor);
            ResultSet rs = pstmt.executeQuery();

            while (rs.next()) {
                int deudaId = rs.getInt("deudaId");
                int idBoleta = rs.getInt("idBoleta");
                Date fechaDeuda = rs.getDate("fechaDeuda");
                boolean estaPagado = rs.getBoolean("estaPagado");
                int montoPagado = rs.getInt("montoPagado");
                int totalFiado = rs.getInt("totalFiado");

                int saldo = totalFiado - montoPagado;
                if (!estaPagado) {
                    deudaTotal += saldo;
                }

                String estado = estaPagado ? "PAGADO" : "PENDIENTE";

                NumberFormat nf = NumberFormat.getInstance(new Locale("es", "CL"));

                modeloHistorial.addRow(new Object[]{
                    idBoleta,
                    fechaDeuda.toString(),
                    "$" + nf.format(totalFiado),
                    "$" + nf.format(montoPagado),
                    "$" + nf.format(saldo),
                    estado
                });
            }

            NumberFormat nf = NumberFormat.getInstance(new Locale("es", "CL"));
            if (deudaTotal > 0) {
                lblPrecioExample.setText("$" + nf.format(deudaTotal));
                lblPrecioExample.setForeground(new java.awt.Color(255, 0, 51)); // Rojo
            } else {
                lblPrecioExample.setText("$0");
                lblPrecioExample.setForeground(new java.awt.Color(0, 153, 0)); // Verde
            }

            rs.close();
            pstmt.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al cargar historial: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            cargarDatosPrueba();
        }
    }

    private void cargarDatosPrueba() {
        NumberFormat nf = NumberFormat.getInstance(new Locale("es", "CL"));
        
        modeloHistorial.addRow(new Object[]{"B001", "2024-01-15", "$150,000", "$50,000", "$100,000", "PENDIENTE"});
        modeloHistorial.addRow(new Object[]{"B002", "2024-02-20", "$80,000", "$80,000", "$0", "PAGADO"});
        modeloHistorial.addRow(new Object[]{"B003", "2024-03-10", "$200,000", "$100,000", "$100,000", "PENDIENTE"});
        
        lblPrecioExample.setText("$200,000");
        lblPrecioExample.setForeground(new java.awt.Color(255, 0, 51));
        
        JOptionPane.showMessageDialog(this,
            "Se están mostrando datos de prueba.\n" +
            "Conexión a base de datos falló.\n\n" +
            "Verifica que:\n" +
            "1. MySQL esté corriendo\n" +
            "2. La base de datos 'vistaalmar' exista\n" +
            "3. Las tablas 'deudas' y 'boletas' existan",
            "Modo Prueba",
            JOptionPane.WARNING_MESSAGE);
    }


    private void cargarDetalleBoleta(int idBoleta) {
        try {
            modeloDetalle.setRowCount(0);

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/vistaalmar", 
                "root", 
                ""
            );

            String sql = "SELECT p.nomProducto, " +
                         "d.cantidad, " +
                         "d.precioUnitario, " +
                         "d.totalPago as subtotal " +
                         "FROM detalleBoletaProductos d " +
                         "INNER JOIN productos p ON d.codProducto = p.codProducto " +
                         "WHERE d.idBoleta = ?";

            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setInt(1, idBoleta);
            ResultSet rs = pstmt.executeQuery();

            NumberFormat nf = NumberFormat.getInstance(new Locale("es", "CL"));

        while (rs.next()) {
            String nombreProducto = rs.getString("nomProducto");
            int cantidad = rs.getInt("cantidad");
            int precioUnitario = rs.getInt("precioUnitario");
            int subtotal = rs.getInt("subtotal");

            System.out.println("Producto: " + nombreProducto + 
                               ", Cantidad: " + cantidad + 
                               ", Precio: " + precioUnitario + 
                               ", Subtotal: " + subtotal);

            modeloDetalle.addRow(new Object[]{
                nombreProducto,
                cantidad,
                "$" + nf.format(precioUnitario),
                "$" + nf.format(subtotal)
            });
        }

        if (modeloDetalle.getRowCount() == 0) {
            System.out.println("No se encontraron productos para la boleta #" + idBoleta);
            modeloDetalle.addRow(new Object[]{
                "Sin productos en esta boleta", "", "", ""
            });
        }

            rs.close();
            pstmt.close();
            conn.close();

        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this,
                "Error: Driver JDBC no encontrado\n" + e.getMessage(),
                "Error de Conexión",
                JOptionPane.ERROR_MESSAGE);
            cargarDetallePrueba();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Error al cargar productos de la boleta:\n" + e.getMessage() +
                "\n\nVerifica que:\n" +
                "1. La tabla 'detalleBoletaProductos' exista\n" + 
                "2. La tabla 'productos' exista\n" +
                "3. La boleta #" + idBoleta + " tenga productos",
                "Error de Base de Datos",
                JOptionPane.ERROR_MESSAGE);
            cargarDetallePrueba();
        }
    }
    
    private void cargarDetallePrueba() {
        NumberFormat nf = NumberFormat.getInstance(new Locale("es", "CL"));

        modeloDetalle.addRow(new Object[]{"Laptop Dell Inspiron", 1, "$800,000", "$800,000"});
        modeloDetalle.addRow(new Object[]{"Mouse Inalámbrico Logitech", 2, "$15,000", "$30,000"});
        modeloDetalle.addRow(new Object[]{"Teclado Mecánico Redragon", 1, "$45,000", "$45,000"});
        modeloDetalle.addRow(new Object[]{"Monitor 24\" Samsung", 1, "$250,000", "$250,000"});
    }
       
       
       
    private void agregarListeners() {
        btnVerProductos.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                verDetalleBoleta();
            }
        });

        btnPagarDeuda.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                abrirPagarDeuda();
            }
        });

        btnCerrar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                volver();
            }
        });

        tablaHistorial.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    filaSeleccionada = tablaHistorial.getSelectedRow();
                    if (filaSeleccionada >= 0) {
                        idBoletaSeleccionada = (int) modeloHistorial.getValueAt(filaSeleccionada, 0);
                        cargarDetalleBoleta(idBoletaSeleccionada);
                    }
                }
            }
        });
    }
    
    
    
    
    private void verDetalleBoleta() {
        int filaSeleccionada = tablaHistorial.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this,
                "Por favor seleccione una deuda para ver el detalle",
                "Aviso",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int idBoleta = (int) modeloHistorial.getValueAt(filaSeleccionada, 0);
        String estado = (String) modeloHistorial.getValueAt(filaSeleccionada, 5);
        
        String mensaje = "Detalle de Boleta #" + idBoleta + "\n" +
                         "Estado: " + estado + "\n\n" +
                         "Los productos de esta boleta se muestran en la tabla inferior.";
        
        JOptionPane.showMessageDialog(this,
            mensaje,
            "Detalle de Boleta",
            JOptionPane.INFORMATION_MESSAGE);
    }
    
    
    private void abrirPagarDeuda() {
        try {
            boolean pagoEspecifico = (filaSeleccionada != -1);

            int deudaTotal = 0;
            int deudaEspecifica = 0;
            int idBoletaEspecifica = -1;

            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/vistaalmar", 
                "root", 
                ""
            );

            if (pagoEspecifico) {
                idBoletaEspecifica = this.idBoletaSeleccionada;

                String sqlEspecifico = "SELECT b.totalFiado, d.montoPagado, d.estaPagado " +
                                     "FROM deudas d " +
                                     "INNER JOIN boletas b ON d.idBoleta = b.idBoleta " +
                                     "WHERE d.rutDeudor = ? AND d.idBoleta = ?";

                PreparedStatement pstmt = conn.prepareStatement(sqlEspecifico);
                pstmt.setInt(1, rutDeudor);
                pstmt.setInt(2, idBoletaEspecifica);
                ResultSet rs = pstmt.executeQuery();

                if (rs.next()) {
                    int totalFiado = rs.getInt("totalFiado");
                    int montoPagado = rs.getInt("montoPagado");
                    boolean estaPagado = rs.getBoolean("estaPagado");
                    deudaEspecifica = totalFiado - montoPagado;

                    if (estaPagado || deudaEspecifica <= 0) {
                        JOptionPane.showMessageDialog(this,
                            "Esta boleta ya está pagada completamente",
                            "Información",
                            JOptionPane.INFORMATION_MESSAGE);
                        rs.close();
                        pstmt.close();
                        conn.close();
                        return;
                    }
                }
                rs.close();
                pstmt.close();

                NumberFormat nf = NumberFormat.getInstance(new Locale("es", "CL"));
                String mensaje = "Boleta #" + idBoletaEspecifica + "\n" +
                               "Deuda específica: $" + nf.format(deudaEspecifica) + "\n\n" +
                               "¿Cómo desea proceder?";

                String[] opciones = {"Pagar solo esta boleta", "Pagar toda la deuda", "Cancelar"};
                int eleccion = JOptionPane.showOptionDialog(this,
                    mensaje,
                    "Opciones de Pago",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    opciones,
                    opciones[0]);

                if (eleccion == 2 || eleccion == -1) { 
                    conn.close();
                    return;
                }

                if (eleccion == 0) {
                    deudaTotal = deudaEspecifica;
                } else {
                    String sqlTotal = "SELECT SUM(b.totalFiado - d.montoPagado) as total " +
                                    "FROM deudas d " +
                                    "INNER JOIN boletas b ON d.idBoleta = b.idBoleta " +
                                    "WHERE d.rutDeudor = ? AND d.estaPagado = 0";

                    PreparedStatement pstmtTotal = conn.prepareStatement(sqlTotal);
                    pstmtTotal.setInt(1, rutDeudor);
                    ResultSet rsTotal = pstmtTotal.executeQuery();

                    if (rsTotal.next()) {
                        deudaTotal = rsTotal.getInt("total");
                    }

                    rsTotal.close();
                    pstmtTotal.close();
                    idBoletaEspecifica = -1; // No pagar boleta específica
                }
            } else {
                String sql = "SELECT SUM(b.totalFiado - d.montoPagado) as total " +
                           "FROM deudas d " +
                           "INNER JOIN boletas b ON d.idBoleta = b.idBoleta " +
                           "WHERE d.rutDeudor = ? AND d.estaPagado = 0";

                PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1, rutDeudor);
                ResultSet rs = pstmt.executeQuery();

                if (rs.next()) {
                    deudaTotal = rs.getInt("total");
                }

                rs.close();
                pstmt.close();
            }

            conn.close();

            if (deudaTotal <= 0) {
                JOptionPane.showMessageDialog(this,
                    "Este cliente no tiene deudas pendientes",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            PagarDeudaDialog dialog;
            if (idBoletaEspecifica > 0) {
                dialog = new PagarDeudaDialog(this, rutDeudor, nombreDeudor, deudaTotal, usuario, permisos, idBoletaEspecifica);
            } else {
                dialog = new PagarDeudaDialog(this, rutDeudor, nombreDeudor, deudaTotal, usuario, permisos);
            }

            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    actualizarTablaDespuesDePago();
                }
            });

            dialog.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al verificar deudas: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void actualizarTablaDespuesDePago() {
        try {
            int filaAnterior = filaSeleccionada;
            int idBoletaAnterior = idBoletaSeleccionada;

            cargarHistorialDeudas();

            if (filaAnterior != -1 && idBoletaAnterior != -1) {
                for (int i = 0; i < modeloHistorial.getRowCount(); i++) {
                    int idBoleta = (int) modeloHistorial.getValueAt(i, 0);
                    if (idBoleta == idBoletaAnterior) {
                        tablaHistorial.setRowSelectionInterval(i, i);
                        filaSeleccionada = i;
                        idBoletaSeleccionada = idBoletaAnterior;
                        cargarDetalleBoleta(idBoletaAnterior);
                        break;
                    }
                }
            }

            JOptionPane.showMessageDialog(this,
                "La información se ha actualizado correctamente",
                "Actualización Exitosa",
                JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al actualizar la tabla: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    private void volver() {
        if (ventanaPadre != null) {
            ventanaPadre.setVisible(true);
        }
        this.dispose();
    }

    /**
     * Exit the Application
     */                     

    
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        if (ventanaPadre != null) {
            ventanaPadre.setVisible(true);
        }
        dispose(); 
    }//GEN-LAST:event_exitForm

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerProductosActionPerformed
        verDetalleBoleta();
    }//GEN-LAST:event_btnVerProductosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // Para probar la ventana
                HistorialDeuda ventana = new HistorialDeuda(12345678, "Juan Pérez", null);
                ventana.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnPagarDeuda;
    private javax.swing.JButton btnVerProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDeudaTotal;
    private javax.swing.JLabel lblHistorial;
    private javax.swing.JLabel lblPrecioExample;
    private javax.swing.JLabel lblProductosBoleta;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblRutExample;
    private javax.swing.JScrollPane panelDetalle;
    private javax.swing.JScrollPane panelHistorial;
    private javax.swing.JTable tablaDetalle;
    private javax.swing.JTable tablaHistorial;
    // End of variables declaration//GEN-END:variables
}
