/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */

/**
 *
 * @author franc
 */
public class NuevoDeudor extends java.awt.Frame {

    /**
     * Creates new form NuevoDeudor
     */
    public NuevoDeudor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        lblRut = new javax.swing.JLabel();
        lblNom = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        lbltitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbltitulo.setText("Registrar nuevo deudor");

        lblRut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRut.setText("RUT:");

        lblNom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNom.setText("Nombre:");

        lblTel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTel.setText("Telefono");

        btnGuardar.setBackground(new java.awt.Color(0, 204, 51));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(255, 0, 51));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Volver");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGap(98, 98, 98)
                                            .addComponent(lblRut, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                            .addGap(89, 89, 89)
                                            .addComponent(lblTel)))
                                    .addGap(28, 28, 28))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                    .addGap(88, 88, 88)
                                    .addComponent(lblNom)))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lbltitulo)
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRut)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNom)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTel)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    
    
    
  
    private boolean validarRUT(String rut) {
    try {
        if (rut == null || rut.trim().isEmpty()) {
            return false;
        }
        
        if (!rut.matches("\\d+")) {
            return false;
        }
        
    
        int rutNum = Integer.parseInt(rut);
        

        return rutNum > 0 && rutNum <= 1000000000;
        
    } catch (NumberFormatException e) {
        return false;
        }
    }    
  
    private boolean validarNombre(String nombre) {
        if (nombre == null || nombre.trim().isEmpty()) {
            return false;
        }
        
        if (nombre.length() < 3 || nombre.length() > 30) {
            return false;
        }
        
        return nombre.matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+");
    }    
    
 
    
    
    private boolean validarTelefono(String telefono) {
        try {
            if (!telefono.matches("\\d+")) {
                return false;
            }
            
            int tel = Integer.parseInt(telefono);
            
            return (telefono.length() == 8 || telefono.length() == 9) && tel > 0;
            
        } catch (NumberFormatException e) {
            return false;
        }
    }
    

    
    
    private void guardarDeudor() {
        String rutStr = txtRut.getText().trim();
        String nombre = txtNom.getText().trim();
        String telefonoStr = txtTel.getText().trim();
        
        if (rutStr.isEmpty() || nombre.isEmpty() || telefonoStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Todos los campos son obligatorios", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!validarRUT(rutStr)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "RUT inválido. Debe contener solo números y ser un RUT chileno válido", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            txtRut.requestFocus();
            return;
        }
        
        if (!validarNombre(nombre)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Nombre inválido. Debe contener solo letras y tener entre 3 y 30 caracteres", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            txtNom.requestFocus();
            return;
        }
        
        if (!validarTelefono(telefonoStr)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Teléfono inválido. Debe contener 8 o 9 dígitos numéricos", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            txtTel.requestFocus();
            return;
        }
        
        int rut = Integer.parseInt(rutStr);
        int telefono = Integer.parseInt(telefonoStr);
        
        java.sql.Connection conexion = null;
        java.sql.PreparedStatement pstmt = null;
        
        try {
            String url = "jdbc:mysql://localhost:3306/vistaalmar";
            String usuario = "root";
            String password = "";
            
            conexion = java.sql.DriverManager.getConnection(url, usuario, password);
            
            String verificarSQL = "SELECT COUNT(*) FROM deudores WHERE rutDeudor = ?";
            pstmt = conexion.prepareStatement(verificarSQL);
            pstmt.setInt(1, rut);
            java.sql.ResultSet rs = pstmt.executeQuery();
            
            if (rs.next() && rs.getInt(1) > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "El deudor con RUT " + rut + " ya existe en el sistema", 
                    "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            String insertSQL = "INSERT INTO deudores (rutDeudor, nomDeudor, telefono) VALUES (?, ?, ?)";
            pstmt = conexion.prepareStatement(insertSQL);
            pstmt.setInt(1, rut);
            pstmt.setString(2, nombre);
            pstmt.setInt(3, telefono);
            
            int filasAfectadas = pstmt.executeUpdate();
            
            if (filasAfectadas > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Deudor registrado exitosamente", 
                    "Éxito", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
                txtRut.setText("");
                txtNom.setText("");
                txtTel.setText("");
                txtRut.requestFocus();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Error al registrar el deudor", 
                    "Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Error de base de datos: " + e.getMessage(), 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } finally {
            try {
                if (pstmt != null) pstmt.close();
                if (conexion != null) conexion.close();
            } catch (java.sql.SQLException e) {
                e.printStackTrace();
            }
        }
    }
    
    
    
    
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarDeudor();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoDeudor().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblNom;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
