
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.time.Month;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author oct88
 */
public class VentaPerdida extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Compra.class.getName());
    private String usuario = "hello";
    private boolean estado = false;
    Connection conex=null;
    Statement stm=null;
    /**
     * Creates new form Compra
     */
    public VentaPerdida() {
        initComponents();
    }
    
    public VentaPerdida(String nuevo, boolean estado) {
        this.usuario = nuevo;
        this.estado = estado;
        initComponents();
        lblTotalPrecio.setText("0");
        conectar();
        customClose();
        lblPrecio.setText("");
        lblStock.setText("");
        
    }
    
    public void customClose(){
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                registrarRetiro();
                System.exit(0);
            }
        });
    }
    
    
    public void registrarRetiro(){
        int valor = Integer.parseInt(usuario);
        try{
            LocalDateTime ahora = LocalDateTime.now();
            Timestamp tiempo = Timestamp.valueOf(ahora);
            stm=conex.createStatement();
            stm.executeUpdate("INSERT INTO accessLog (rutUsuario, tipoAccion, fechaAccion) VALUES("+valor+",0,'"+ tiempo +"')");
            stm.close();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error en database: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        return;
    }
    
    public void conectar(){
        String url="jdbc:mysql://localhost:3306/vistaalmar";
        String usuario="root";
        String pass="";
        try{
            conex=DriverManager.getConnection(url,usuario,pass);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"error en conexion "+ex,"error",1);
        }       
    }
    
    boolean checkCantidad(int cantidad, int codigo){
        try{
            stm = conex.createStatement();
            ResultSet fila = stm.executeQuery("SELECT stock FROM productos WHERE codProducto=" + codigo);
            while(fila.next()){
                int valor = fila.getInt("stock");
                if(cantidad > valor){
                    return true;
                }
            }
            return false;
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"error en conexion "+ex,"error",1);
            return false;
        }
    }
    
    public boolean confirmarCodigo(int codigo){
        DefaultTableModel modelo = (DefaultTableModel) tblCarro.getModel();
        if(modelo.getRowCount()==0){
            return false;
        }
        int codigoCheck;
        for(int i = 0; i < modelo.getRowCount(); i++){
            Object valor = modelo.getValueAt(i, 0);
            String valor1 = valor.toString();
            codigoCheck = Integer.parseInt(valor1);
            if(codigoCheck == codigo){
                return true;
            }       
        }
        return false;
    }
    public void actualizarTotal(){
        DefaultTableModel modelo = (DefaultTableModel) tblCarro.getModel();
        int total = 0;
        for(int i = 0; i < modelo.getRowCount(); i++){
            String valor = modelo.getValueAt(i, 4).toString();
            total = total + Integer.parseInt(valor);
        }
        lblTotalPrecio.setText(String.valueOf(total));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgDescuentos = new javax.swing.ButtonGroup();
        btgOpcionDescuentos = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnPrincipal = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        cmbBorrar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        lblUnidad = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCarro = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        cmbBuscar = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lblTotalPrecio = new javax.swing.JLabel();
        btnProveedores = new javax.swing.JButton();
        cmbBorrarTodo = new javax.swing.JButton();
        txtUnidad = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        lblPrecioLabel = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbDestruccion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegresar.setText("Cerrar Sesión");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnPrincipal.setText("Menu Principal");
        btnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar Perdida");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        cmbBorrar.setText("Borrar Item");
        cmbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBorrarActionPerformed(evt);
            }
        });

        btnIngresar.setText("Ingresar Item");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        lblCodigo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCodigo.setText("Codigo Producto");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombre.setText("Nombre Producto");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        lblUnidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnidad.setText("Cantidad Unitaria");

        tblCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Cantidad Perdida", "Precio Unitario", "Total Perdido", "Tipo Perdida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCarro);

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscar.setText(" Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        cmbBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Total Perdido: ");

        lblTotalPrecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalPrecio.setText("jLabel2");

        btnProveedores.setText("Menu Venta");
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });

        cmbBorrarTodo.setText("Limpiar Carro");
        cmbBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBorrarTodoActionPerformed(evt);
            }
        });

        lblPrecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrecio.setText("Precio");

        lblPrecioLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPrecioLabel.setText("Precio:");

        lblStock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStock.setText("Precio");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Stock:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Tipo Perdida");

        cmbDestruccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Producto Robado", "Producto Vencido", "Producto Destruido" }));
        cmbDestruccion.setSelectedIndex(-1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPrecioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblStock, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(btnProveedores)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(33, 33, 33)
                                .addComponent(cmbDestruccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(290, 452, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addComponent(jScrollPane2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnConfirmar)
                .addGap(180, 180, 180))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(cmbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(cmbBorrarTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCodigo)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPrecio)
                                    .addComponent(lblPrecioLabel)
                                    .addComponent(lblStock)
                                    .addComponent(jLabel2))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUnidad))))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbDestruccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalPrecio)
                            .addComponent(jLabel1))
                        .addGap(44, 44, 44)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(236, 236, 236))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBorrarTodoActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblCarro.getModel();
        modelo.setRowCount(0);
        actualizarTotal();
    }//GEN-LAST:event_cmbBorrarTodoActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        this.dispose();
        new Venta(usuario,estado).setVisible(true);
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void cmbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBuscarActionPerformed
        try{
            if(cmbBuscar.getSelectedItem()== null){
                return;
            }
            String item = cmbBuscar.getSelectedItem().toString();
            String partes[] = item.split("-");
            int codigo = Integer.parseInt(partes[0]);
            int precio = 0;
            int stock = 0;
            stm = conex.createStatement();
            ResultSet fila = stm.executeQuery("SELECT precioActual, stock FROM productos WHERE codProducto =" + codigo);
            if(fila.next()){
                precio = fila.getInt("precioActual");
                stock = fila.getInt("Stock");
                lblPrecio.setText(String.valueOf(precio));
                lblStock.setText(String.valueOf(stock));
            }
        }catch (SQLException rollbackEx) {
            JOptionPane.showMessageDialog(null, "Error crítico Revisar Base De Datos" + rollbackEx.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cmbBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        cmbBuscar.removeAllItems();
        String codigo = txtCodigo.getText().trim();
        String nombre = txtNombre.getText().trim();
        if(nombre.length()==0){
            return;
        }
        if(codigo.length()== 0 && nombre.length() == 0){
            return;
        }
        int codigoCheck;
        if(!codigo.matches("\\d+")){
            codigoCheck = -3;
        }
        else{
            codigoCheck = Integer.parseInt(codigo);
        }
        try{
            stm = conex.createStatement();
            ResultSet lista = stm.executeQuery("SELECT codProducto, nomProducto FROM productos WHERE nomProducto LIKE '%" + nombre + "%' OR codProducto = " + codigoCheck);
            String nombreLista = "";
            String codigoLista = "";
            int codigoLista2 = 0;
            String sentenciaFinal;
            while(lista.next()){
                nombreLista = lista.getString("nomProducto");
                codigoLista2 = lista.getInt("codProducto");
                codigoLista = String.valueOf(codigoLista2);
                sentenciaFinal = codigoLista + "-" + nombreLista;
                cmbBuscar.addItem(sentenciaFinal);
            }
            cmbBuscar.setSelectedIndex(0);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error en database: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if(cmbBuscar.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "Escoja Un Producto Primero. Para Ello: \n  1) Escriba un Codigo y/o Nombre de Producto(s) A Buscar En Las Dos Primeras Casillas \n 2) Presione El Boton Buscar \n 3) En la Lista de Busqueda Al Lado del Boton Buscar, Busque Su Producto Y Seleccionalo", "Falta el Producto", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(cmbDestruccion.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(null, "Seleccione el Tipo de Perdida","Faltan Datos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String unidadString = txtUnidad.getText().trim();
        if(unidadString.matches("\\d+")){
            if(Integer.parseInt(unidadString)<=0){
                JOptionPane.showMessageDialog(null, "Cantidades de Productos deben ser Mayor a 0","Error de Formulario", JOptionPane.WARNING_MESSAGE);
                return;
            }
            int precioUnidad = Integer.parseInt(lblPrecio.getText());
            int cantidadProductos = Integer.parseInt(unidadString);
            int totalPrecio =  precioUnidad * cantidadProductos * -1;
            String tipoPerdida = cmbDestruccion.getSelectedItem().toString();
            String totalPrecio1 = String.valueOf(totalPrecio);
            String item = cmbBuscar.getSelectedItem().toString();
            String[] parts = item.split("-", 2);
            String codigo = parts[0];
            if(confirmarCodigo(Integer.parseInt(codigo))){
                JOptionPane.showMessageDialog(null, "No se Pueden Repetir Items en el Carro \nBorre el Item del Carro e Ingreselo Nuevamente\ncon los datos actualizados","Error de Formulario", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(checkCantidad(cantidadProductos, Integer.parseInt(codigo))){
                JOptionPane.showMessageDialog(null, "Cantidad de Perdida excede el Stock","Error de Formulario", JOptionPane.WARNING_MESSAGE);
                return;
            }
            String nombre = parts[1];
            DefaultTableModel modelo = (DefaultTableModel) tblCarro.getModel();
            Object data[] = {
                codigo,
                nombre,
                cantidadProductos,
                precioUnidad,
                totalPrecio1,
                tipoPerdida
            };
            modelo.addRow(data);
            actualizarTotal();
            txtUnidad.setText("");
            cmbDestruccion.setSelectedIndex(-1);
        }
        else{
            JOptionPane.showMessageDialog(null, "Ingrese Cantidad de Productos a Fiar y Comprar","Error de Formulario", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void cmbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBorrarActionPerformed
        int registro = tblCarro.getSelectedRow();
        if(registro == -1){
            JOptionPane.showMessageDialog(null, "Seleccione un Item del Carro","Item No Seleccionado", JOptionPane.WARNING_MESSAGE);
        }
        DefaultTableModel modelo = (DefaultTableModel) tblCarro.getModel();
        modelo.removeRow(registro);
        actualizarTotal();
    }//GEN-LAST:event_cmbBorrarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        DefaultTableModel modelo1 = (DefaultTableModel) tblCarro.getModel();
        int size = modelo1.getRowCount();
        if(size == 0){
            JOptionPane.showMessageDialog(null, "El carro esta vacio");
            return;
        }
        Object[] opciones = {"Sí", "No"};
        int respuesta =JOptionPane.showOptionDialog(
            null,
            "¿Desea Confirmar La Perdida?",
            "Confirmar Perdida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE,
            null,
            opciones,
            opciones[0]
        );
        if(respuesta==1){
            return;
        }
        int user = Integer.parseInt(usuario);
        int totalPago = Integer.parseInt(lblTotalPrecio.getText());
        String medioPagos = "Perdida";
        LocalDate ahora = LocalDate.now();
        try{
            conex.setAutoCommit(false);
            
            int valor = 0;
            
            stm = conex.createStatement();
            stm.executeUpdate(
                    "INSERT INTO boletas (rutUsuario, fechaTramite, medioPago, totalPagados, totalFiado) "
                    + "Values(" + user +", '"+ ahora +"','"+ medioPagos +"'," + totalPago + ",0)", 
                    Statement.RETURN_GENERATED_KEYS);
            ResultSet rs = stm.getGeneratedKeys();
            if (rs.next()) {
                valor = rs.getInt(1);  
            }
            rs.close();
            stm.close();
                     
            DefaultTableModel modelo = (DefaultTableModel) tblCarro.getModel();
            for(int i = 0; i < modelo.getRowCount(); i++){
                int codigoProducto = Integer.parseInt(modelo.getValueAt(i, 0).toString());
                String tipoTransaccion = modelo.getValueAt(i, 5).toString();
                int cantidadUnitaria = Integer.parseInt(modelo.getValueAt(i, 2).toString());
                int precioUnitario = Integer.parseInt(modelo.getValueAt(i, 3).toString());
                int totalProducto = Integer.parseInt(modelo.getValueAt(i, 4).toString());
                float descuento = -1f;
                stm = conex.createStatement();
                stm.executeUpdate(
                    "INSERT INTO detalleBoletaProductos (idBoleta, codProducto, cantidad, cantidadFiado, precioUnitario, descuento, totalPago, totalFiado, tipoTransaccion) "
                    + "Values(" + valor +", "+ codigoProducto +","+ cantidadUnitaria +",0," + precioUnitario + "," + descuento + "," + totalProducto + ",0,'" + tipoTransaccion + "')");
                stm.close();
                
                stm = conex.createStatement();
                
                stm.executeUpdate("UPDATE productos SET stock = stock - " + cantidadUnitaria + " WHERE codProducto = " + codigoProducto);
                
                stm.close();
            }
            
            conex.commit();
            JOptionPane.showMessageDialog(null, "Perdida Registrada Exitosamente");
            conex.setAutoCommit(true);
            this.dispose();
            new HistorialBoletas(usuario,estado).setVisible(true);
        }catch(SQLException ex){
            try {
                conex.rollback();
                JOptionPane.showMessageDialog(null, "Error en Base de Datos, Operación Revertida: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            } catch (SQLException rollbackEx) {
                JOptionPane.showMessageDialog(null, "Error crítico: rollback falló: " + rollbackEx.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }finally{
            try{
                conex.setAutoCommit(true);
            }catch (SQLException rollbackEx) {
                JOptionPane.showMessageDialog(null, "Error crítico Revisar Base De Datos" + rollbackEx.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        registrarRetiro();
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalActionPerformed
        this.dispose();
        new MenuPrincipal(usuario, estado).setVisible(true);
    }//GEN-LAST:event_btnPrincipalActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        registrarRetiro();
        this.dispose();
        new MenuAcceso().setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Compra().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgDescuentos;
    private javax.swing.ButtonGroup btgOpcionDescuentos;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnPrincipal;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton cmbBorrar;
    private javax.swing.JButton cmbBorrarTodo;
    private javax.swing.JComboBox<String> cmbBuscar;
    private javax.swing.JComboBox<String> cmbDestruccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecioLabel;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTotalPrecio;
    private javax.swing.JLabel lblUnidad;
    private javax.swing.JTable tblCarro;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUnidad;
    // End of variables declaration//GEN-END:variables
}
